// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyA9hJd3QpXcvrIla-uK0oeutTl21nOWU',
    appId: '1:149109781313:web:31ca6e3e9ecba0f597a7c0',
    messagingSenderId: '149109781313',
    projectId: 'jol-app-47422',
    authDomain: 'jol-app-47422.firebaseapp.com',
    databaseURL: 'https://jol-app-47422-default-rtdb.firebaseio.com',
    storageBucket: 'jol-app-47422.firebasestorage.app',
    measurementId: 'G-GF5W6CH02H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnwNK8LLT28xeXL4LkCVpcWKE1b9imSeI',
    appId: '1:149109781313:android:d780bf1cc05b664797a7c0',
    messagingSenderId: '149109781313',
    projectId: 'jol-app-47422',
    databaseURL: 'https://jol-app-47422-default-rtdb.firebaseio.com',
    storageBucket: 'jol-app-47422.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcmlPv9OAtVhq-HzaWf6Uzq4xYTG07lRk',
    appId: '1:149109781313:ios:a3cf51d814d0cd8297a7c0',
    messagingSenderId: '149109781313',
    projectId: 'jol-app-47422',
    databaseURL: 'https://jol-app-47422-default-rtdb.firebaseio.com',
    storageBucket: 'jol-app-47422.firebasestorage.app',
    iosBundleId: 'com.example.jolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcmlPv9OAtVhq-HzaWf6Uzq4xYTG07lRk',
    appId: '1:149109781313:ios:a3cf51d814d0cd8297a7c0',
    messagingSenderId: '149109781313',
    projectId: 'jol-app-47422',
    databaseURL: 'https://jol-app-47422-default-rtdb.firebaseio.com',
    storageBucket: 'jol-app-47422.firebasestorage.app',
    iosBundleId: 'com.example.jolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyA9hJd3QpXcvrIla-uK0oeutTl21nOWU',
    appId: '1:149109781313:web:2c4ecd877d16bf9597a7c0',
    messagingSenderId: '149109781313',
    projectId: 'jol-app-47422',
    authDomain: 'jol-app-47422.firebaseapp.com',
    databaseURL: 'https://jol-app-47422-default-rtdb.firebaseio.com',
    storageBucket: 'jol-app-47422.firebasestorage.app',
    measurementId: 'G-3EWC27SMN5',
  );
}
